/**
 * The authoritative list of what this package exposes.
 *
 * Two tests hold the code to it: a runtime check that each subpath's value
 * exports are exactly the list below, and a type fixture that names every type
 * so `tsc` fails if one disappears. Type-only exports never show up in a
 * runtime key set, which is why they need the second test at all.
 *
 * Adding or removing an export is an edit to this file in the same commit. That
 * is the whole point: a private package still has a surface, and a surface that
 * can grow silently is one nobody reviews.
 */

/** `@cortexkit/openai-auth-core` — the command seam. */
export const ROOT_VALUE_EXPORTS = [
  'MODAL_COMMANDS',
  'OPENAI_ACCOUNT_COMMAND_NAME',
  'OPENAI_CACHEKEEP_COMMAND_NAME',
  'OPENAI_DUMP_COMMAND_NAME',
  'OPENAI_KILLSWITCH_COMMAND_NAME',
  'OPENAI_LOGGING_COMMAND_NAME',
  'OPENAI_QUOTA_COMMAND_NAME',
  'OPENAI_RESET_COMMAND_NAME',
  'OPENAI_ROUTING_COMMAND_NAME',
  'applyCommand',
  'buildDialogPayload',
  'scrubKnobs',
] as const

export const ROOT_TYPE_EXPORTS = [
  'ApplyRequest',
  'ApplyResult',
  'CommandContext',
  'CommandModalName',
  'HostCommandBodies',
  'HostCommandBody',
  'OpenDialogPayload',
] as const

/** `@cortexkit/openai-auth-core/internal` — host support past the seam. */
export const INTERNAL_VALUE_EXPORTS = [
  'ACCOUNT_FILE_NAME',
  'ACCOUNT_STATE_FILE_NAME',
  'AccountRemovedDuringRefreshError',
  'CLIENT_ID',
  'CODEX_CLIENT_ID',
  'CODEX_ISSUER',
  'CUSTODY_DEPS_INCOMPLETE',
  'CUSTODY_EXCLUDED',
  'CUSTODY_MANIFEST_TENANT',
  'CUSTODY_OWNING_PROVIDER',
  'CUSTODY_OWNING_SERVE',
  'CUSTODY_OWNING_SHAPE',
  'CUSTODY_REFUSE',
  'CUSTODY_TOMBSTONE_PREFIX',
  // The three vendored-client names the host needs to locate and open the vault
  // socket. Named deliberately: the vendored client also carries transport
  // internals that are not part of this package's surface.
  'ClaustrumClient',
  'ClaustrumCredentialCache',
  'detectClaustrumConnection',
  'getDefaultClaustrumConnectionPath',
  'CustodyTombstoneRefreshError',
  'DEFAULT_KILLSWITCH_THRESHOLDS',
  'FALLBACK_REFRESH_LOCK_TTL_MS',
  'FallbackAccountManager',
  'HTML_ERROR',
  'HTML_SUCCESS',
  'ISSUER',
  'NON_TRANSIENT_REFRESH_RETRY_DELAY_MS',
  'OAUTH_POLLING_SAFETY_MARGIN_MS',
  'OAUTH_PORT',
  'PRIMARY',
  'QuotaManager',
  'RESERVED_ACCOUNT_ID',
  'RESERVED_ACCOUNT_ID_ERROR',
  'ResetCreditError',
  'ResetRedemptionError',
  'SECONDARY',
  'USER_AGENT_PRODUCT',
  'acquireRefreshFileLock',
  'assertFallbackAccountIdAllowed',
  'assertNoCustodyTombstoneMaterial',
  'assertNotCustodyTombstone',
  'base64UrlEncode',
  'beginAccountLogin',
  'beginDeviceAuth',
  'buildAuthorizeUrl',
  'buildQuotaOperationError',
  'buildRefreshOperationError',
  'buildUserAgent',
  'canonicalCustodyTombstone',
  'claimResetAttempt',
  'claustrumMode',
  'codexRefreshFn',
  'completeDeviceAuth',
  'consumeResetCredit',
  'countEligibleResetCredits',
  'createLogger',
  'custodied',
  'custodyManifestHandles',
  'custodySlotFingerprint',
  'custodyTombstoneKey',
  'deriveStatePath',
  'enrolled',
  'enrolling',
  'errorMessage',
  'escapeHtml',
  'evaluateResetPrecondition',
  'exchangeCodeForTokens',
  'excluded',
  'extractAccountId',
  'extractAccountIdFromClaims',
  'finalizeResetAttempt',
  'flowCleanup',
  'fallbackRefreshLockName',
  'flushForTest',
  'flushLogs',
  'formatQuotaBackoffMessage',
  'formatRefreshBackoffMessage',
  'generatePKCE',
  'getKillswitchThresholdsForAccount',
  'getQuotaCheckIntervalMs',
  'getRefreshIntervalMs',
  'hashRefreshToken',
  'initLogger',
  'isApiKeyAccount',
  'isCompleteQuotaHeaderFrame',
  'isCostZeroingEnabled',
  'isKillswitchEnabled',
  'isLostMarkerRaceError',
  'isOAuthAccount',
  'isRecord',
  'isReservedAccountId',
  'isResetCreditEligible',
  'isSafeResetAccountKey',
  'isTransientQuotaError',
  'isTransientRefreshError',
  'isValidApiBaseURL',
  'killswitchPassesPolicy',
  'killswitchRetryAfterSeconds',
  'listResetCredits',
  'loadAccounts',
  'manifestRevision',
  'migrateIfNeeded',
  'mutateAccounts',
  'normalizeAccount',
  'normalizeQuotaHeaders',
  'normalizeWham',
  'normalizeWsFrame',
  'openUrl',
  'parseJwtClaims',
  'parseRetryAfter',
  'quotaBackoffActive',
  'quotaSnapshotPassesPolicy',
  'quotaWindowResetIsPast',
  'readConfigRosterIds',
  'readCustodyManifest',
  'reconcileFallbackCustody',
  'redact',
  'redactStrings',
  'refreshAllQuota',
  'refreshBackoffActive',
  'refreshInert',
  'renderResetCoordinatorResult',
  'resetLoggerForTest',
  'resetOAuthStateForTest',
  'resetWindowIsExhausted',
  'resolveMidStreamRateLimitResetAt',
  'resolveFallbackAccess',
  'runResetCreditRedemption',
  'saveAccountState',
  'saveAccounts',
  'selectCreditToSpend',
  'setLogLevel',
  'shouldFallbackStatus',
  'stampVaultProvenance',
  'startOAuthServer',
  'stopOAuthServer',
  'toResetIso',
  'tokenFingerprint',
  'tombstoned',
  'upsertAccount',
  'verifyServedFallbackIdentity',
  'waitForOAuthCallback',
  'whamUsageFn',
  'withAccountStoreTransaction',
  'writeClaustrumModeAndTransition',
  'writeJsonAtomic',
] as const

export const INTERNAL_TYPE_EXPORTS = [
  'AccountBase',
  'AccountManagerOptions',
  'AccountOperationError',
  'AccountPaths',
  'AccountQuotaWindow',
  'AccountRefreshError',
  'AccountRuntimeEntry',
  'AccountRuntimeState',
  'AccountStateSaveScope',
  'AccountStorage',
  'AccountStorageLike',
  'ApiKeyAccount',
  'ApplyRequest',
  'ApplyResult',
  'BeginAccountLoginOptions',
  'BeginAccountLoginResult',
  'CacheKeepManager',
  'CommandModalName',
  'DeviceAuthInit',
  'FallbackAccount',
  'IdTokenClaims',
  'IngestAccount',
  'InitLoggerOptions',
  'KillswitchConfig',
  'KillswitchThresholds',
  'Level',
  'OAuthAccount',
  'OAuthQuotaSnapshot',
  'OpenDialogPayload',
  'PendingOAuth',
  'PkceCodes',
  'ProviderHttpError',
  'ProviderQuotaFn',
  'ProviderRefreshFn',
  'QuotaEntry',
  'QuotaManagerOptions',
  'QuotaWindowName',
  'RefreshAllQuotaDeps',
  'RefreshAllQuotaOptions',
  'RefreshAllQuotaResult',
  'ResetAccountState',
  'ResetConsumeKind',
  'ResetConsumeOutcome',
  'ResetCredit',
  'ResetCreditErrorKind',
  'ResetCreditList',
  'ResetInFlight',
  'ResetLastOutcome',
  'ResetLocalAmbiguousOutcome',
  'ResetPrecondition',
  'ResetRedemptionErrorKind',
  'ResetRedemptionOutcome',
  'ResetResolvedTarget',
  'ResetSelectedCredit',
  'ResetStateByAccount',
  'ResetStateDeps',
  'ResetTargetIdentity',
  'RoutingMode',
  'RpcNotification',
  'RunResetCreditDeps',
  'RunResetCreditInput',
  'RunResetCreditResult',
  'SidebarQuotaReading',
  'SidebarQuotaSnapshot',
  'TokenResponse',
] as const
